// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/.well-known/webfinger.ts";
import * as $1 from "./routes/[name].tsx";
import * as $2 from "./routes/api/inbox.ts";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/api/m/[id].ts";
import * as $5 from "./routes/api/m/index.ts";
import * as $6 from "./routes/api/register.ts";
import * as $7 from "./routes/api/u/[id].ts";
import * as $8 from "./routes/api/u/[id]/followers.ts";
import * as $9 from "./routes/api/u/index.ts";
import * as $10 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/.well-known/webfinger.ts": $0,
    "./routes/[name].tsx": $1,
    "./routes/api/inbox.ts": $2,
    "./routes/api/joke.ts": $3,
    "./routes/api/m/[id].ts": $4,
    "./routes/api/m/index.ts": $5,
    "./routes/api/register.ts": $6,
    "./routes/api/u/[id].ts": $7,
    "./routes/api/u/[id]/followers.ts": $8,
    "./routes/api/u/index.ts": $9,
    "./routes/index.tsx": $10,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
